# Generated by Django 2.2 on 2019-04-29 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_fname', models.CharField(max_length=255)),
                ('emp_lname', models.CharField(max_length=255)),
                ('emp_phone', models.CharField(max_length=10)),
                ('emp_address', models.EmailField(max_length=255)),
                ('type', models.CharField(choices=[('01', 'weavers'), ('02', 'supervisors'), ('03', 'engineer')], default='01', max_length=3)),
                ('emp_salary', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('mac_id', models.AutoField(primary_key=True, serialize=False)),
                ('mac_name', models.CharField(max_length=255)),
                ('mac_sum', models.CharField(max_length=255)),
                ('mac_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('datetime', models.DateField()),
                ('state', models.CharField(choices=[('01', 'Pending'), ('02', 'Inprogress'), ('03', 'Succeed')], default='01', max_length=3)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('part_desc', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('minimum_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reports.Employee')),
                ('eng_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Machine_Part',
            fields=[
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reports.Part', unique=True)),
                ('unit', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Machine', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance_Machine_Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Maintenance')),
                ('machine_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Machine_Part')),
            ],
        ),
        migrations.AddField(
            model_name='machine_part',
            name='maintenance',
            field=models.ManyToManyField(through='reports.Maintenance_Machine_Part', to='reports.Maintenance'),
        ),
        migrations.AlterUniqueTogether(
            name='machine_part',
            unique_together={('part', 'machine')},
        ),
    ]
