# Generated by Django 2.2 on 2019-05-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='image',
            field=models.ImageField(null=True, upload_to='images/machine/'),
        ),
    ]
