# Generated by Django 2.2 on 2019-04-29 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reports.Employee')),
                ('eng_type', models.CharField(max_length=255)),
            ],
        ),
    ]
