# Generated by Django 2.2 on 2019-05-03 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_cart_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Category')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Machine')),
            ],
        ),
    ]
