# Generated by Django 2.2 on 2019-05-03 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_machine_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='for_machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reports.Machine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='for_machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reports.Machine'),
            preserve_default=False,
        ),
    ]
