# Generated by Django 2.2 on 2019-05-07 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_machine_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance_machine_part',
            name='machine_part',
        ),
        migrations.RemoveField(
            model_name='maintenance_machine_part',
            name='maintenance',
        ),
        migrations.DeleteModel(
            name='Machine_Part',
        ),
        migrations.DeleteModel(
            name='Maintenance_Machine_Part',
        ),
    ]
