# Generated by Django 2.2 on 2019-05-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20190503_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='part_name',
            new_name='part_code',
        ),
    ]
